name: Build spring-social-slideshare project

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}
      - name: Run all checks
        run: ./gradlew check jacocoTestReport --stacktrace
      - name: Upload the build reports of 'spring-social-slideshare'
        uses: actions/upload-artifact@v2
        with:
          name: spring-social-slideshare
          path: ./spring-social-slideshare/build/reports
        if: ${{ always() }}
      - name: Upload the build reports of 'spring-social-samples'
        uses: actions/upload-artifact@v2
        with:
          name: spring-social-samples
          path: ./spring-social-samples/build/reports
        if: ${{ always() }}
